### Question 1

In [ ]:
 We use ordinal encoding to preserve order of categorical data i.e. cold, warm, hot; low, medium, high. 
And we use label encoding or one hot for categorical data, where there's no order in data i.e. dog, cat, 
whale.

The main difference between these two techniques is the way they assign values to categories

In [ ]:
# how to choose one of them
Suppose you have a categorical variable "rating" with three categories "low", "medium", and "high", and
you want to use this variable to predict a target variable using a machine learning model. In this case,
you might choose to use label encoding because the values assigned to each category are arbitrary and do
not have any inherent order or rank. Label encoding would assign the values 0, 1, and 2 to the categories
"low", "medium", and "high", respectively, and the machine learning model would treat these values as
numeric inputs.

On the other hand, suppose you have a categorical variable "age group" with categories "child", "teenager",
"young adult", "adult", and "senior", and you want to use this variable to predict a target variable.
In this case, you might choose to use ordinal encoding because the categories have a natural order or rank.
Ordinal encoding would assign values 1, 2, 3, 4, and 5 to the categories, respectively, and the 
machine learning model would be able to capture the inherent order of the categories

### Question 2

In [ ]:
Target Guided Ordinal Encoding is a technique used to encode categorical variables based on the target 
variable, where the values are assigned to the categories based on the relationship between the category 
and the target variable. The purpose of this encoding technique is to capture the information contained in 
the categorical variable that is relevant to the target variable, which can improve the performance of
machine learning models.

In [ ]:
# Example for target guided ordinal encoding

Suppose you have a dataset of customers who have purchased products from an online store, and you want to 
build a machine learning model to predict whether a customer will make another purchase in the future. 
One of the features in the dataset is "product category", which has several categories such as "electronics", 
"clothing", "home decor", and "books". You suspect that the category of the product a customer has purchased
might be a relevant factor in predicting whether they will make another purchase in the future.

To encode this categorical feature, you might use Target Guided Ordinal Encoding, which would assign an 
ordinal value to each category based on the average purchase rate for each category. For example,
if "electronics" has the highest purchase rate, it would be assigned the value 1, followed by "clothing" 
with value 2, "home decor" with value 3, and "books" with value 4. This encoding would capture the 
information contained in the "product category" feature that is relevant to the target variable 
(purchase rate), and the resulting encoded feature would be used as input to the machine learning model

### Question 3

In [ ]:
Covariance is a measure of the degree to which two random variables vary together. 
It measures the extent to which two variables are related, and in what way. A positive covariance 
indicates that the two variables tend to vary together, while a negative covariance indicates that they 
tend to vary in opposite directions.

In [ ]:
Covariance is important in statistical analysis because it provides insights into the relationships between
variables. It can help us to identify trends and patterns in data, and to understand how changes in one 
variable affect another. Covariance is used in many different statistical analyses, including regression 
analysis, factor analysis, and principal component analysis. It is a fundamental concept in statistics and
is used extensively in data analysis, machine learning, and other areas of research.

### Question 4

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [4]:
data = {'Color': ['red', 'green', 'blue', 'green', 'red', 'blue'],
        'Size': ['small', 'medium', 'large', 'small', 'medium', 'large'],
        'Material': ['wood', 'metal', 'plastic', 'wood', 'plastic', 'metal']}
df = pd.DataFrame(data)

In [5]:
encoder = LabelEncoder()

In [6]:
df['Color']=encoder.fit_transform(df['Color'])
df['Size']=encoder.fit_transform(df['Size'])
df['Material']=encoder.fit_transform(df['Material'])

In [7]:
df

Color  Size  Material
0      2     2         2
1      1     1         0
2      0     0         1
3      1     2         2
4      2     1         1
5      0     0         0

### Question 5

In [8]:
import numpy as np

# Create a sample dataset
age = [30, 40, 25, 35, 45]
income = [50000, 60000, 40000, 55000, 70000]
education = [12, 16, 10, 14, 18]


data = np.array([age, income, education])

cov_matrix = np.cov(data)

print(cov_matrix)


[[6.25e+01 8.75e+04 2.50e+01]
 [8.75e+04 1.25e+08 3.50e+04]
 [2.50e+01 3.50e+04 1.00e+01]]


### Question 6

In [ ]:
For categorical variables like "Gender", "Education Level", and "Employment Status", we can use different 
encoding methods depending on the nature of the variable and the algorithm we are planning to use. 
Here are some possible encoding methods and why we might choose them for each variable:

In [ ]:
# for Gender:
 "Gender" has only two possible values (Male and Female), we can use binary encoding or label encoding to 
represent the variable. Binary encoding would encode Male as 0 and Female as 1, while label encoding 
would encode Male as 0 and Female as 1. 

In [ ]:
# for Education:
Since "Education Level" has multiple categories, we can use one-hot encoding or target encoding to represent
the variable. One-hot encoding would create a binary variable for each category, with a value of 1 
indicating that the observation belongs to that category and a value of 0 indicating that it does not. 
Target encoding would replace each category with the mean of the target variable for that category.
One-hot encoding might be preferred if we are using a tree-based model that can handle high-dimensional data,
while target encoding might be preferred if we are using a linear model that assumes a smooth relationship
between the variable and the outcome.

In [ ]:
# for Employment Status
"Employment Status" has multiple categories, we can use one-hot encoding or target encoding to represent 
the variable. One-hot encoding would create a binary variable for each category, with a value of 1 
indicating that the observation belongs to that category and a value of 0 indicating that it does not. 
Target encoding would replace each category with the mean of the target variable for that category. 
One-hot encoding might be preferred if we are using a tree-based model that can handle high-dimensional data,
while target encoding might be preferred if we are using a linear model that assumes a smooth relationship
between the variable and the outcome